# Generated by Django 5.2.7 on 2026-01-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaignConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('twilio_content_sid', models.CharField(help_text='Twilio Content Template SID', max_length=255)),
                ('content_variables', models.JSONField(default=list, help_text='List of content variables with serial and value')),
                ('contact_filter_type', models.CharField(choices=[('all', 'All Contacts'), ('selected', 'Selected Contacts')], default='all', max_length=20)),
                ('selected_contact_ids', models.JSONField(blank=True, default=list, help_text="List of contact IDs from JobAdder (only used if filter_type is 'selected')")),
                ('schedule_type', models.CharField(choices=[('now', 'Send Now'), ('scheduled', 'Schedule for Later')], default='now', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="When to send the campaign (only used if schedule_type is 'scheduled')", null=True)),
                ('chatbot_template', models.CharField(choices=[('ai_call', 'AI Call')], default='ai_call', help_text='Template for AI chatbot interactions', max_length=50)),
                ('ai_instructions', models.TextField(blank=True, help_text='Custom instructions for AI to handle responses to this campaign')),
                ('from_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_contacts', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_failed', models.IntegerField(default=0)),
                ('messages_delivered', models.IntegerField(default=0)),
                ('messages_read', models.IntegerField(default=0)),
                ('responses_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='organizations.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='organizations.organizationplatform')),
            ],
            options={
                'db_table': 'whatsapp_campaign_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(help_text='Contact ID from JobAdder', max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('message_sid', models.CharField(blank=True, help_text='Twilio Message SID', max_length=255)),
                ('message_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='pending', max_length=20)),
                ('message_content', models.TextField(blank=True, help_text='The actual message content sent')),
                ('error_code', models.CharField(blank=True, max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('conversation_json', models.JSONField(default=list, help_text='Complete conversation history with this contact')),
                ('has_responded', models.BooleanField(default=False)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_count', models.IntegerField(default=0)),
                ('ai_conversation_active', models.BooleanField(default=False, help_text='Whether AI chatbot is actively conversing with this contact')),
                ('ai_conversation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('ai_conversation_outcome', models.CharField(blank=True, help_text="Outcome of AI conversation (e.g., 'successful', 'unsuccessful', 'abandoned')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='whatsapp_campaign.whatsappcampaignconfig')),
            ],
            options={
                'db_table': 'whatsapp_campaign_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignconfig',
            index=models.Index(fields=['organization', 'status'], name='whatsapp_ca_organiz_b43a57_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignconfig',
            index=models.Index(fields=['scheduled_at'], name='whatsapp_ca_schedul_066968_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignconfig',
            index=models.Index(fields=['status', 'schedule_type'], name='whatsapp_ca_status_a420b5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignreport',
            index=models.Index(fields=['campaign', 'message_status'], name='whatsapp_ca_campaig_80b358_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignreport',
            index=models.Index(fields=['contact_id'], name='whatsapp_ca_contact_e00807_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignreport',
            index=models.Index(fields=['contact_phone'], name='whatsapp_ca_contact_ace917_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignreport',
            index=models.Index(fields=['message_sid'], name='whatsapp_ca_message_4b1275_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcampaignreport',
            index=models.Index(fields=['has_responded'], name='whatsapp_ca_has_res_1b95f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcampaignreport',
            unique_together={('campaign', 'contact_id')},
        ),
    ]
