# Generated by Django 5.2.7 on 2026-01-07 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaignconfig',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappcampaignreport',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
