# Generated by Django 5.2.7 on 2025-12-29 06:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lead_generation', '0001_initial'),
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether marketing automation is active for this organization')),
                ('exclude_agencies', models.BooleanField(default=True, help_text='If True, skip companies identified as recruitment agencies')),
                ('opportunity_stage', models.IntegerField(blank=True, help_text='Stage ID to assign to created opportunities (optional)', null=True)),
                ('opportunity_owners', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='List of user IDs who will own the created opportunities', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_automation_configs', to='organizations.organization')),
                ('platform', models.ForeignKey(help_text='Platform/ATS integration to use', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_automation_configs', to='organizations.organizationplatform')),
            ],
            options={
                'verbose_name': 'Marketing Automation Config',
                'verbose_name_plural': 'Marketing Automation Configs',
                'db_table': 'marketing_automation_config',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='marketing_a_organiz_39d140_idx'), models.Index(fields=['is_active'], name='marketing_a_is_acti_ce1cf0_idx')],
                'unique_together': {('organization', 'platform')},
            },
        ),
    ]
