# Generated by Django 5.2.7 on 2025-12-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lead_generation', '0002_marketingautomationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingautomationconfig',
            name='opportunity_stage',
            field=models.CharField(blank=True, help_text='Stage ID to assign to created opportunities (optional)', null=True),
        ),
    ]
