# Generated by Django 5.2.7 on 2025-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lead_generation', '0003_alter_marketingautomationconfig_opportunity_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenerationconfig',
            name='find_contacts_without_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadgenerationconfig',
            name='is_company_address_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leadgenerationconfig',
            name='is_contacts_item_required',
            field=models.BooleanField(default=True),
        ),
    ]
