# Generated by Django 5.2.7 on 2026-01-13 07:12

import dirtyfields.dirtyfields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lead_generation', '0004_leadgenerationconfig_find_contacts_without_company_and_more'),
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadgenerationconfig',
            name='is_contacts_item_required',
            field=models.BooleanField(default=False, help_text="If True, skip companies that don't have contact information"),
        ),
        migrations.CreateModel(
            name='LeadGenerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_candidates_processed', models.IntegerField(default=0)),
                ('total_candidates_failed', models.IntegerField(default=0)),
                ('total_companies_extracted', models.IntegerField(default=0)),
                ('total_companies_created', models.IntegerField(default=0)),
                ('total_companies_skipped', models.IntegerField(default=0)),
                ('total_companies_failed', models.IntegerField(default=0)),
                ('total_contacts_extracted', models.IntegerField(default=0)),
                ('total_contacts_created', models.IntegerField(default=0)),
                ('total_contacts_failed', models.IntegerField(default=0)),
                ('candidates_with_no_resume', models.IntegerField(default=0)),
                ('candidates_with_no_data', models.IntegerField(default=0)),
                ('companies_skipped_related', models.IntegerField(default=0)),
                ('companies_skipped_no_address', models.IntegerField(default=0)),
                ('companies_skipped_existing', models.IntegerField(default=0)),
                ('companies_skipped_no_contact', models.IntegerField(default=0)),
                ('created_company_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='All company IDs created during this report', size=None)),
                ('created_contact_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='All contact IDs created during this report', size=None)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, null=True)),
                ('execution_log', models.TextField(blank=True, null=True)),
                ('candidate_ids_processed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('candidate_ids_failed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ai_lead_generation.leadgenerationconfig')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_generation_reports', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CandidateLeadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.IntegerField()),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('companies_extracted', models.IntegerField(default=0)),
                ('companies_created', models.IntegerField(default=0)),
                ('companies_skipped', models.IntegerField(default=0)),
                ('contacts_extracted', models.IntegerField(default=0)),
                ('contacts_created', models.IntegerField(default=0)),
                ('had_resume', models.BooleanField(default=False)),
                ('resume_text_length', models.IntegerField(default=0)),
                ('extracted_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_company_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('created_contact_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Contact IDs created for this candidate', size=None)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='ai_lead_generation.leadgenerationreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MarketingAutomationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='running', help_text='Current status of the automation run', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the automation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the automation completed', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total duration of the run in seconds', null=True)),
                ('total_companies_fetched', models.IntegerField(default=0, help_text='Total number of companies fetched from platform')),
                ('companies_processed', models.IntegerField(default=0, help_text='Number of companies that were analyzed')),
                ('companies_skipped', models.IntegerField(default=0, help_text='Number of companies skipped (no contact info, agencies, etc.)')),
                ('companies_hiring', models.IntegerField(default=0, help_text='Number of companies identified as actively hiring')),
                ('companies_failed', models.IntegerField(default=0, help_text='Number of companies that failed to process')),
                ('opportunities_created', models.IntegerField(default=0, help_text='Total number of opportunities created')),
                ('opportunities_failed', models.IntegerField(default=0, help_text='Number of opportunities that failed to create')),
                ('agencies_detected', models.IntegerField(default=0, help_text='Number of recruitment agencies detected')),
                ('agencies_excluded', models.IntegerField(default=0, help_text='Number of agencies excluded from processing')),
                ('job_titles_found', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='All unique job titles found during this run', size=None)),
                ('companies_with_opportunities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='List of company IDs that had opportunities created', size=None)),
                ('skipped_no_contact', models.IntegerField(default=0, help_text='Companies skipped due to missing contact information')),
                ('skipped_no_hiring', models.IntegerField(default=0, help_text="Companies skipped as they're not hiring")),
                ('skipped_no_job_titles', models.IntegerField(default=0, help_text='Companies skipped due to no job titles found')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the run failed', null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detailed error information and stack traces', null=True)),
                ('ai_api_calls', models.IntegerField(default=0, help_text='Number of AI API calls made during this run')),
                ('platform_api_calls', models.IntegerField(default=0, help_text='Number of platform API calls made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations about this run')),
                ('config', models.ForeignKey(blank=True, help_text='Configuration used for this automation run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ai_lead_generation.marketingautomationconfig')),
                ('organization', models.ForeignKey(help_text='Organization this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_automation_reports', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Marketing Automation Report',
                'verbose_name_plural': 'Marketing Automation Reports',
                'db_table': 'marketing_automation_report',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadgenerationreport',
            index=models.Index(fields=['organization', '-created_at'], name='ai_lead_gen_organiz_42d7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='leadgenerationreport',
            index=models.Index(fields=['status', '-created_at'], name='ai_lead_gen_status_1cdb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateleadresult',
            index=models.Index(fields=['report', 'processed_successfully'], name='ai_lead_gen_report__8f5da5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateleadresult',
            index=models.Index(fields=['candidate_id'], name='ai_lead_gen_candida_77acef_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingautomationreport',
            index=models.Index(fields=['organization', '-started_at'], name='marketing_a_organiz_bdafe4_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingautomationreport',
            index=models.Index(fields=['status'], name='marketing_a_status_5001d1_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingautomationreport',
            index=models.Index(fields=['-started_at'], name='marketing_a_started_a1b7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingautomationreport',
            index=models.Index(fields=['config', '-started_at'], name='marketing_a_config__94d0aa_idx'),
        ),
    ]
