# Generated by Django 5.2.7 on 2025-10-20 06:52

import dirtyfields.dirtyfields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('twilio_sid', models.CharField(db_index=True, help_text='Twilio Phone Number SID', max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='The purchased phone number in E.164 format', max_length=128, region=None, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='Friendly name for the phone number', max_length=255)),
                ('country_code', models.CharField(help_text='ISO country code (e.g., US, CA, GB)', max_length=2)),
                ('area_code', models.CharField(blank=True, help_text='Area code of the phone number', max_length=10)),
                ('locality', models.CharField(blank=True, help_text='City or locality of the phone number', max_length=255)),
                ('region', models.CharField(blank=True, help_text='State or region of the phone number', max_length=255)),
                ('number_type', models.CharField(choices=[('LOCAL', 'Local'), ('TOLL_FREE', 'Toll Free'), ('MOBILE', 'Mobile'), ('SHORT_CODE', 'Short Code')], default='LOCAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RELEASED', 'Released'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('voice_capable', models.BooleanField(default=True, help_text='Can make/receive voice calls')),
                ('sms_capable', models.BooleanField(default=True, help_text='Can send/receive SMS messages')),
                ('mms_capable', models.BooleanField(default=False, help_text='Can send/receive MMS messages')),
                ('fax_capable', models.BooleanField(default=False, help_text='Can send/receive faxes')),
                ('voice_url', models.URLField(blank=True, help_text='URL for handling incoming voice calls')),
                ('voice_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10)),
                ('sms_url', models.URLField(blank=True, help_text='URL for handling incoming SMS messages')),
                ('sms_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10)),
                ('status_callback_url', models.URLField(blank=True, help_text='URL for status callbacks')),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly cost in USD', max_digits=10)),
                ('release_date', models.DateTimeField(blank=True, help_text='Date when the number was released', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this phone number')),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the user's primary phone number")),
                ('twilio_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from Twilio API')),
                ('organization', models.ForeignKey(help_text='Organization who owns this phone number', on_delete=django.db.models.deletion.CASCADE, related_name='twilio_phone_numbers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Twilio Phone Number',
                'verbose_name_plural': 'Twilio Phone Numbers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='core_twilio_organiz_795e5c_idx'), models.Index(fields=['phone_number'], name='core_twilio_phone_n_a2eb16_idx'), models.Index(fields=['twilio_sid'], name='core_twilio_twilio__9df349_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
