# Generated by Django 5.2.7 on 2025-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfeature',
            options={},
        ),
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('AI_CALL', 'AI Call'), ('AI_SMS', 'AI SMS'), ('AI_WHATSAPP', 'AI WhatsApp'), ('AI_CV_FORMATTER', 'AI CV Formatter'), ('AI_CANDIDATE_SKILL_SEARCH', 'AI Candidate Skill Search'), ('AWR_COMPLIANCE', 'AWR Compliance'), ('AI_GDPR', 'AI GDPR'), ('AI_LEAD_GENERATION', 'AI Lead Generation'), ('AI_DOCUMENT_VERIFY', 'AI Document Verify'), ('AI_BDM_SALES_ENGINE', 'AI BDM Sales Engine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='planfeature',
            unique_together={('feature', 'name')},
        ),
    ]
