# Generated by Django 5.2.7 on 2025-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('AI_CALL', 'Ai_call'), ('AI_SMS', 'Ai_sms'), ('AI_WHATSAPP', 'Ai_whatsapp')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
