# Generated by Django 5.2.7 on 2026-01-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_planfeature_options_alter_feature_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('AI_CALL', 'AI Call'), ('AI_SMS', 'AI SMS'), ('AI_WHATSAPP', 'AI WhatsApp'), ('AI_CV_FORMATTER', 'AI CV Formatter'), ('AI_CANDIDATE_SKILL_SEARCH', 'AI Candidate Skill Search'), ('AWR_COMPLIANCE', 'AWR Compliance'), ('AI_GDPR', 'AI GDPR'), ('AI_LEAD_GENERATION', 'AI Lead Generation'), ('AI_DOCUMENT_VERIFY', 'AI Document Verify'), ('AI_BDM_SALES_ENGINE', 'AI BDM Sales Engine'), ('WHATSAPP_CAMPAIGN', 'Whats app Campaign')], max_length=50),
        ),
    ]
