# Generated by Django 5.2.7 on 2026-01-14 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='des_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='usage_fee_included',
            field=models.BooleanField(default=True),
        ),
    ]
