# Generated by Django 5.2.7 on 2025-10-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='redirect_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
