# Generated by Django 5.2.7 on 2025-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_platform_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='response_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
