# Generated by Django 5.2.7 on 2025-12-30 05:43

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
        ('phone_number', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACEHOLDER', 'Placeholder'), ('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('PAUSED', 'Paused'), ('REMOVED', 'Removed')], default='HIDDEN', max_length=50)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AIMessageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_status_for_sms', models.PositiveIntegerField()),
                ('jobad_status_for_sms', models.CharField(default='Current', max_length=255)),
                ('sms_time_after_status_update', models.IntegerField()),
                ('status_for_unsuccessful_sms', models.PositiveIntegerField()),
                ('status_for_successful_sms', models.PositiveIntegerField()),
                ('status_when_sms_is_send', models.PositiveIntegerField(default=0)),
                ('twilio_sid', models.CharField(blank=True, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, null=True)),
                ('whatsapp_template_sid', models.CharField(blank=True, null=True)),
                ('type', models.CharField(choices=[('AI_CALL', 'Ai_call'), ('AI_SMS', 'Ai_sms'), ('AI_WHATSAPP', 'Ai_whatsapp')], default='AI_SMS', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_number.twiliophonenumber')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationplatform')),
            ],
            options={
                'unique_together': {('organization', 'platform', 'phone')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AIPhoneCallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_call_if_primary_answer_negative', models.BooleanField(default=False)),
                ('application_status_for_calling', models.PositiveIntegerField()),
                ('jobad_status_for_calling', models.CharField(max_length=255)),
                ('calling_time_after_status_update', models.IntegerField()),
                ('status_for_unsuccessful_call', models.PositiveIntegerField()),
                ('status_for_successful_call', models.PositiveIntegerField()),
                ('status_when_call_is_placed', models.PositiveIntegerField(default=0)),
                ('voice_id', models.CharField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_number.twiliophonenumber')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationplatform')),
            ],
            options={
                'unique_together': {('organization', 'platform')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InterviewMessageConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_phone', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_email', models.CharField(blank=True, max_length=255, null=True)),
                ('application_id', models.PositiveIntegerField()),
                ('candidate_id', models.PositiveIntegerField()),
                ('jobad_id', models.PositiveIntegerField()),
                ('ai_instruction', models.TextField()),
                ('conversation_json', models.JSONField(help_text='Conversation messages in JSON format')),
                ('message_count', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('AI_CALL', 'Ai_call'), ('AI_SMS', 'Ai_sms'), ('AI_WHATSAPP', 'Ai_whatsapp')], default='AI_SMS', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In_progress'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=20)),
                ('ai_dicision', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InterviewTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_id', models.PositiveIntegerField(blank=True, null=True)),
                ('candidate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('interview_status', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_decision', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('call_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('call_status', models.CharField(blank=True, max_length=100, null=True)),
                ('disconnection_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('AI_CALL', 'Ai_call'), ('AI_SMS', 'Ai_sms'), ('AI_WHATSAPP', 'Ai_whatsapp')], default='AI_CALL', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In_progress'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InterviewCallConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_sid', models.CharField(max_length=100, unique=True)),
                ('application_id', models.PositiveIntegerField()),
                ('candidate_id', models.PositiveIntegerField()),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_email', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('job_id', models.PositiveIntegerField()),
                ('conversation_text', models.TextField(help_text='Full conversation in text format')),
                ('conversation_json', models.JSONField(help_text='Conversation messages in JSON format')),
                ('message_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewtaken')),
            ],
            options={
                'db_table': 'interview_conversations',
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionConfigConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.aiphonecallconfig')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.primaryquestion')),
            ],
            options={
                'unique_together': {('question', 'config')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionMessageConfigConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.aimessageconfig')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.primaryquestion')),
            ],
            options={
                'unique_together': {('question', 'config')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
