# Generated by Django 5.2.7 on 2025-12-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtaken',
            name='candidate_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewtaken',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewtaken',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
