# Generated by Django 5.2.7 on 2025-11-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=100, unique=True)),
                ('application_id', models.CharField(max_length=100)),
                ('candidate_id', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=100)),
                ('conversation_text', models.TextField(help_text='Full conversation in text format')),
                ('conversation_json', models.JSONField(help_text='Conversation messages in JSON format')),
                ('message_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'db_table': 'interview_conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
