# Generated by Django 5.2.7 on 2026-01-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='company_name',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='company_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
