# Generated by Django 5.2.7 on 2025-12-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewmessageconversation_candidate_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewtaken',
            old_name='ai_dicision',
            new_name='ai_decision',
        ),
    ]
