# Generated by Django 5.2.7 on 2025-12-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewtaken_candidate_email_and_more'),
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
        ('phone_number', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aimessageconfig',
            unique_together={('organization', 'platform', 'phone', 'type')},
        ),
    ]
