# Generated by Django 5.2.7 on 2025-11-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewconversation',
            name='application_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewconversation',
            name='candidate_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='interviewconversation',
            name='job_id',
            field=models.PositiveIntegerField(),
        ),
    ]
