# Generated by Django 5.2.7 on 2026-01-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_callrequest_company_name_callrequest_company_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=10)),
                ('call_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.callrequest')),
            ],
        ),
    ]
