# Generated by Django 5.2.7 on 2025-12-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_aimessageconfig_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiphonecallconfig',
            name='document_upload_link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiphonecallconfig',
            name='sent_document_upload_link',
            field=models.BooleanField(default=False),
        ),
    ]
