# Generated by Django 5.2.7 on 2026-01-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_meetingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingbooking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
