# Generated by Django 5.2.7 on 2026-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_meetingbooking_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
