# Generated by Django 5.2.7 on 2026-01-22 11:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_callrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
