# Generated by Django 5.2.7 on 2025-12-17 05:33

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWRConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_status_ids', models.JSONField(default=list, help_text='List of status IDs to filter placements')),
                ('selected_payment_types', models.JSONField(default=list, help_text='List of payment type names to filter placements')),
                ('placement_started_before_days', models.IntegerField(default=84, help_text='Number of days before which placement should have started (minimum 7)')),
                ('email_template_name', models.CharField(default='emails/awr_compliance_email.html', help_text='Email template to use', max_length=255)),
                ('email_sender', models.EmailField(help_text='Email address to send from', max_length=254)),
                ('email_reply_to', models.EmailField(help_text='Email address to receive replies', max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationplatform')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AWRTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_id', models.IntegerField(help_text='Placement ID from platform')),
                ('contact_email', models.EmailField(help_text='Contact email from placement', max_length=254)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awr_compliance.awrconfig')),
            ],
            options={
                'unique_together': {('config', 'placement_id')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
