# Generated by Django 5.2.7 on 2026-01-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awr_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awrconfig',
            name='email_reply_to',
            field=models.EmailField(blank=True, help_text='Email address to receive replies', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='awrconfig',
            name='email_sender',
            field=models.EmailField(blank=True, help_text='Email address to send from', max_length=254, null=True),
        ),
    ]
