# Generated by Django 5.2.7 on 2025-12-08 11:16

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPREmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('should_use_last_application_date', models.BooleanField(default=False)),
                ('should_use_last_placement_date', models.BooleanField(default=False)),
                ('should_use_last_note_creatation_date', models.BooleanField(default=False)),
                ('should_use_activity_creation_date', models.BooleanField(default=False)),
                ('should_use_candidate_update_date', models.BooleanField(default=False)),
                ('interval_from_last_action', models.CharField(choices=[('6_MONTH', '6 Months'), ('12_MONTH', '12 Months'), ('24_MONTH', '24 Months'), ('36_MONTH', '36 Months'), ('48_MONTH', '48 Months')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationplatform')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GDPREmailTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('candidate_id', models.PositiveIntegerField()),
                ('ai_instruction', models.TextField()),
                ('conversation_json', models.JSONField(help_text='Conversation messages in JSON format')),
                ('message_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN_PROGRESS', 'In_progress'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=20)),
                ('ai_dicision', models.CharField(blank=True, max_length=100, null=True)),
                ('is_candidate_agree', models.BooleanField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_gdpr.gdpremailconfig')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
