# Generated by Django 5.2.7 on 2025-11-25 12:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False, help_text='If true, this section cannot be disabled')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CV Section',
                'verbose_name_plural': 'CV Sections',
                'db_table': 'cv_sections',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CVFormatterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status_for_formatting', models.CharField(default='Current', help_text='Only format CVs from jobs in this status', max_length=50)),
                ('enabled_sections', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=['Full Name', 'Email Address', 'Phone Number', 'Address', 'Professional Summary', 'Professional Experience', 'Education', 'Skills', 'Certifications', 'Languages', 'Areas of Expertise', 'Areas for improvement & recommendations'], help_text='List of CV sections to extract', size=None)),
                ('upload_with_logo', models.BooleanField(default=True, help_text='Upload formatted CV with company logo')),
                ('upload_without_logo', models.BooleanField(default=True, help_text='Upload formatted CV without company logo')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_formatter_config', to='organizations.organization')),
                ('platform', models.ForeignKey(help_text='Recruitment platform (e.g., JobAdder)', on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationplatform')),
            ],
            options={
                'verbose_name': 'CV Formatter Configuration',
                'verbose_name_plural': 'CV Formatter Configurations',
                'db_table': 'cv_formatter_config',
                'unique_together': {('organization', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='CVFormattingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(max_length=255)),
                ('candidate_id', models.IntegerField()),
                ('candidate_name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('download', 'Download'), ('extraction', 'Text Extraction'), ('ai_processing', 'AI Processing'), ('pdf_generation', 'PDF Generation'), ('upload', 'Upload')], max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_formatting_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'CV Formatting Log',
                'verbose_name_plural': 'CV Formatting Logs',
                'db_table': 'cv_formatting_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attachment_id'], name='cv_formatti_attachm_5802a3_idx'), models.Index(fields=['candidate_id'], name='cv_formatti_candida_08b278_idx'), models.Index(fields=['organization', 'created_at'], name='cv_formatti_organiz_c1a9c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormattedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.CharField(db_index=True, max_length=255)),
                ('candidate_id', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('download_failed', 'Download Failed'), ('extraction_failed', 'Text Extraction Failed'), ('parsing_failed', 'Parsing Failed'), ('ai_failed', 'AI Processing Failed'), ('pdf_generation_failed', 'PDF Generation Failed'), ('upload_failed', 'Upload Failed')], default='success', max_length=50)),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted CV data from AI')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatted_cvs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Formatted CV',
                'verbose_name_plural': 'Formatted CVs',
                'db_table': 'formatted_cvs',
                'indexes': [models.Index(fields=['attachment_id', 'organization'], name='formatted_c_attachm_b059da_idx'), models.Index(fields=['candidate_id'], name='formatted_c_candida_a56731_idx'), models.Index(fields=['status'], name='formatted_c_status_e26468_idx')],
                'unique_together': {('attachment_id', 'organization')},
            },
        ),
    ]
