# Generated by Django 5.2.7 on 2025-12-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_formatter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvformattinglog',
            name='organization',
        ),
        migrations.DeleteModel(
            name='CVSection',
        ),
        migrations.DeleteModel(
            name='CVFormattingLog',
        ),
    ]
