# Generated by Django 5.2.7 on 2025-12-18 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationplatform_status_organizationuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISkillSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_radius_km', models.IntegerField(default=20, help_text='Radius in kilometers to search for candidates from job location', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('candidate_status_ids', models.JSONField(default=list, help_text='List of candidate status IDs to include in search (e.g., active, inactive, archived)')),
                ('jobad_status_for_skill_search', models.CharField(default='Live', help_text='Job ad status to trigger skill search', max_length=50)),
                ('minimum_skill_match_percentage', models.IntegerField(default=50, help_text='Minimum percentage of skills that must match', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('consider_employment_history', models.BooleanField(default=True, help_text='Whether to consider employment history in skill matching')),
                ('process_cv_for_skills', models.BooleanField(default=True, help_text='Extract skills from CV using AI if candidate has no skills listed')),
                ('max_candidates_per_job', models.IntegerField(default=50, help_text='Maximum number of candidates to return per job', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('auto_apply_matched_candidates', models.BooleanField(default=True, help_text='Automatically create applications for matched candidates')),
                ('auto_apply_status_name', models.CharField(default='AI Available Candidate', help_text='Status name to set for auto-applied candidates', max_length=100)),
                ('send_whatsapp_notifications', models.BooleanField(default=True, help_text='Send WhatsApp messages to matched candidates')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable AI skill search for this organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_skill_search_config', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'AI Skill Search Configuration',
                'verbose_name_plural': 'AI Skill Search Configurations',
                'db_table': 'ai_skill_search_config',
            },
        ),
        migrations.CreateModel(
            name='JobSkillCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ad_id', models.IntegerField(db_index=True, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_location_city', models.CharField(max_length=100)),
                ('required_skills', models.JSONField(default=list, help_text='List of skills extracted by AI from job description')),
                ('nearby_cities', models.JSONField(default=list, help_text='List of cities within search radius')),
                ('job_description', models.JSONField(default=dict, help_text='Job description data used for skill extraction')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('total_candidates_matched', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skill_caches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Job Skill Cache',
                'verbose_name_plural': 'Job Skill Caches',
                'db_table': 'job_skill_cache',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSkillMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(db_index=True)),
                ('job_ad_id', models.IntegerField(db_index=True)),
                ('matched_skills', models.JSONField(default=list, help_text='Skills that matched between candidate and job')),
                ('match_percentage', models.FloatField(default=0.0, help_text='Percentage of required skills matched')),
                ('match_source', models.CharField(choices=[('direct_skills', 'Direct Skills'), ('employment_history', 'Employment History'), ('cv_extraction', 'CV Extraction')], help_text='Source of the skill match', max_length=50)),
                ('application_created', models.BooleanField(default=False)),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill_matches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Candidate Skill Match',
                'verbose_name_plural': 'Candidate Skill Matches',
                'db_table': 'candidate_skill_match',
                'ordering': ['-created_at'],
                'unique_together': {('candidate_id', 'job_ad_id')},
            },
        ),
    ]
