# Generated by Django 5.2.7 on 2026-01-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_skill_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiskillsearchconfig',
            name='auto_apply_status_name',
        ),
        migrations.AddField(
            model_name='aiskillsearchconfig',
            name='auto_apply_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiskillsearchconfig',
            name='auto_apply_matched_candidates',
            field=models.BooleanField(default=False, help_text='Automatically create applications for matched candidates'),
        ),
        migrations.AlterField(
            model_name='aiskillsearchconfig',
            name='consider_employment_history',
            field=models.BooleanField(default=False, help_text='Whether to consider employment history in skill matching'),
        ),
        migrations.AlterField(
            model_name='aiskillsearchconfig',
            name='jobad_status_for_skill_search',
            field=models.CharField(default='Current', help_text='Job ad status to trigger skill search', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiskillsearchconfig',
            name='process_cv_for_skills',
            field=models.BooleanField(default=False, help_text='Extract skills from CV using AI if candidate has no skills listed'),
        ),
        migrations.AlterField(
            model_name='aiskillsearchconfig',
            name='send_whatsapp_notifications',
            field=models.BooleanField(default=False, help_text='Send WhatsApp messages to matched candidates'),
        ),
    ]
