import os
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))


def get_skills_collection() -> dict:
    return {
        "skills": [
            {
                "categoryId": 3220,
                "name": "Accounting",
                "subCategories": [
                    {
                        "name": "Accountant - Chartered / CPA",
                        "subCategoryId": 36126,
                        "skills": [{"name": "Tax knowledge", "skillId": 2066}],
                    },
                    {"name": "Accountant - Cost", "subCategoryId": 36127},
                    {"name": "Accountant - Credit & Risk", "subCategoryId": 36128},
                    {"name": "Accountant - Financial", "subCategoryId": 36129},
                    {
                        "name": "Accountant - Forensic / Advisory",
                        "subCategoryId": 36130,
                    },
                    {"name": "Accountant - Payroll", "subCategoryId": 36131},
                    {"name": "Accountant - Systems", "subCategoryId": 36141},
                    {"name": "Accountant - Tax", "subCategoryId": 36142},
                    {"name": "Accountant - Treasury", "subCategoryId": 36143},
                    {"name": "Accounts Clerk", "subCategoryId": 36144},
                    {"name": "Accounts Payable", "subCategoryId": 36145},
                    {"name": "Accounts Receivable", "subCategoryId": 36146},
                    {"name": "Administration", "subCategoryId": 36135},
                    {"name": "Auditor / Professional Services", "subCategoryId": 36136},
                    {"name": "Bookkeeper", "subCategoryId": 36137},
                    {"name": "Consulting / Business Services", "subCategoryId": 36138},
                    {"name": "Finance Manager", "subCategoryId": 36139},
                    {"name": "Financial Controller", "subCategoryId": 36140},
                    {"name": "Insolvency Practitioner", "subCategoryId": 36132},
                    {"name": "Management Accountant", "subCategoryId": 36133},
                    {"name": "Purchasing / Inventory", "subCategoryId": 36134},
                ],
            },
            {
                "categoryId": 3221,
                "name": "Admin / Secretarial / Office Support",
                "subCategories": [
                    {"name": "Administration", "subCategoryId": 36147},
                    {"name": "Contracts Administrator", "subCategoryId": 36148},
                    {"name": "Data Entry Clerk", "subCategoryId": 36149},
                    {"name": "Executive Assistant", "subCategoryId": 36150},
                    {"name": "Office Junior / Assistant", "subCategoryId": 36151},
                    {"name": "Office Manager", "subCategoryId": 36152},
                    {"name": "Personal Assistant", "subCategoryId": 36153},
                    {"name": "Receptionist", "subCategoryId": 36154},
                    {"name": "Secretary", "subCategoryId": 36155},
                    {"name": "Other", "subCategoryId": 36156},
                ],
            },
            {
                "categoryId": 3222,
                "name": "Advertising / Media / Publishing",
                "subCategories": [
                    {"name": "Account Manager", "subCategoryId": 36157},
                    {"name": "Advertising - Creative Services", "subCategoryId": 36158},
                    {"name": "Advertising Specialist", "subCategoryId": 36159},
                    {"name": "Journalism / Copywriter", "subCategoryId": 36160},
                    {"name": "Publishing", "subCategoryId": 36161},
                ],
            },
            {
                "categoryId": 3223,
                "name": "Agribusiness & Farming",
                "subCategories": [
                    {"name": "Agribusiness Manager", "subCategoryId": 36162},
                    {"name": "Agronomist", "subCategoryId": 36163},
                    {"name": "Aquiculture / Fish Farmer", "subCategoryId": 36164},
                    {"name": "Farmer / Farm Hand", "subCategoryId": 36165},
                    {"name": "Forestry Planner / Modeller", "subCategoryId": 36166},
                    {"name": "Grower", "subCategoryId": 36167},
                    {"name": "Picker", "subCategoryId": 36168},
                    {"name": "Viticulture", "subCategoryId": 36169},
                ],
            },
            {
                "categoryId": 3224,
                "name": "Architecture & Interior Design",
                "subCategories": [
                    {"name": "Architect", "subCategoryId": 36170},
                    {"name": "CAD / Draftsperson", "subCategoryId": 36171},
                    {"name": "Interior Designer", "subCategoryId": 36172},
                    {"name": "Landscape Architect", "subCategoryId": 36173},
                    {"name": "Lighting Specialist", "subCategoryId": 36174},
                    {"name": "Project Manager", "subCategoryId": 36175},
                    {"name": "Technician", "subCategoryId": 36176},
                ],
            },
            {
                "categoryId": 3225,
                "name": "Arts & Entertainment",
                "subCategories": [
                    {"name": "Actors / Dancers / Singers", "subCategoryId": 36177},
                    {"name": "Animation / Cartoonist", "subCategoryId": 36178},
                    {"name": "Artist / Painter", "subCategoryId": 36179},
                    {"name": "Illustration", "subCategoryId": 36180},
                    {"name": "Museum", "subCategoryId": 36181},
                    {"name": "Musician", "subCategoryId": 36182},
                    {"name": "Photography", "subCategoryId": 36183},
                    {"name": "Producer", "subCategoryId": 36184},
                    {"name": "TV / Film / Radio", "subCategoryId": 36185},
                    {"name": "Other", "subCategoryId": 36186},
                ],
            },
            {
                "categoryId": 3226,
                "name": "Banking & Finance",
                "subCategories": [
                    {"name": "Analyst", "subCategoryId": 36187},
                    {"name": "Bank Officer / Teller", "subCategoryId": 36188},
                    {"name": "Banking - Compliance", "subCategoryId": 36189},
                    {"name": "Business & Corporate Banking", "subCategoryId": 36190},
                    {"name": "Client Services", "subCategoryId": 36191},
                    {"name": "Credit & Collections", "subCategoryId": 36192},
                    {"name": "Financial Planning", "subCategoryId": 36198},
                    {"name": "Funds Management", "subCategoryId": 36199},
                    {"name": "Investment Banking", "subCategoryId": 36200},
                    {"name": "Manager", "subCategoryId": 36201},
                    {"name": "Mortgages / Lending", "subCategoryId": 36202},
                    {"name": "Retail / Consumer Banking", "subCategoryId": 36203},
                    {"name": "Settlements", "subCategoryId": 36193},
                    {"name": "Stock Broking", "subCategoryId": 36194},
                    {"name": "Superannuation", "subCategoryId": 36195},
                    {"name": "Treasury and/or Risk Specialist", "subCategoryId": 36196},
                    {"name": "Other", "subCategoryId": 36197},
                ],
            },
            {
                "categoryId": 3228,
                "name": "Call Centre & Customer Service",
                "subCategories": [
                    {"name": "Call Center Operator", "subCategoryId": 36219},
                    {"name": "Call Centre - Inbound", "subCategoryId": 36220},
                    {"name": "Call Centre - Outbound", "subCategoryId": 36221},
                    {"name": "Customer Service", "subCategoryId": 36222},
                    {"name": "Manager", "subCategoryId": 36223},
                    {"name": "Team Leader", "subCategoryId": 36224},
                    {"name": "Telemarketing", "subCategoryId": 36225},
                ],
            },
            {
                "categoryId": 15850,
                "name": "Construction Crane Lifting",
                "subCategories": [
                    {"name": "Appointed Person(AP)", "subCategoryId": 198575},
                    {"name": "Crane Site Supervisor(SS)", "subCategoryId": 198577},
                    {"name": "Crane Supervisor(CS)", "subCategoryId": 198576},
                    {"name": "Crane Operator", "subCategoryId": 198578},
                ],
            },
            {
                "categoryId": 3227,
                "name": "Construction Plant Operator",
                "subCategories": [
                    {
                        "name": "180 Excavator Operator Above 10t",
                        "subCategoryId": 50378,
                        "skills": [
                            {"name": "CSCS Skilled Labourer", "skillId": 91548},
                            {"name": "CPCS Card", "skillId": 91549},
                            {"name": "NPORS Card", "skillId": 91550},
                            {"name": "MPQC Card", "skillId": 91551},
                        ],
                    },
                    {
                        "name": "360 Excavator Operator Above 10t - Lifting Operations",
                        "subCategoryId": 58286,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2336},
                            {"name": "CPCS Red", "skillId": 2337},
                            {"name": "CSCS Card", "skillId": 2338},
                            {"name": "NPORS", "skillId": 2339},
                            {
                                "name": "Geotechnical Awareness for Operatives Certificate",
                                "skillId": 2372,
                            },
                            {"name": "Dredging Experience", "skillId": 2429},
                            {"name": "Leveling Experience", "skillId": 2430},
                            {"name": "Breaker Experience", "skillId": 2431},
                        ],
                    },
                    {
                        "name": "360 Excavator Operator Above 10t - Tracked",
                        "subCategoryId": 50360,
                        "skills": [
                            {"name": "CPCS - RED", "skillId": 2096},
                            {"name": "CPCS - BLUE", "skillId": 2097},
                            {"name": "NPORS", "skillId": 2098},
                            {"name": "CSCS Card", "skillId": 2099},
                            {
                                "name": "Geotechnical Awareness for Operatives Certificate",
                                "skillId": 2373,
                            },
                            {"name": "Dredging Experience", "skillId": 2426},
                            {"name": "Leveling Experience", "skillId": 2427},
                            {"name": "Breaker Experience", "skillId": 2428},
                        ],
                    },
                    {
                        "name": "360 Excavator Operator Above 10t - Wheeled (Rubber Duck)",
                        "subCategoryId": 50361,
                        "skills": [
                            {"name": "CPCS - RED", "skillId": 2101},
                            {"name": "CPCS - BLUE", "skillId": 2102},
                            {"name": "NPORS", "skillId": 2103},
                            {"name": "CSCS Card", "skillId": 2104},
                            {
                                "name": "Geotechnical Awareness for Operatives Certificate",
                                "skillId": 2374,
                            },
                            {"name": "Dredging Experience", "skillId": 2432},
                            {"name": "Leveling Experience", "skillId": 2433},
                            {"name": "Breaker Experience", "skillId": 2434},
                        ],
                    },
                    {
                        "name": "360 Excavator Operator Below 10t - Lifting Operations",
                        "subCategoryId": 58285,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2340},
                            {"name": "CPCS Red", "skillId": 2341},
                            {"name": "CSCS Card", "skillId": 2342},
                            {"name": "NPORS", "skillId": 2343},
                            {
                                "name": "Geotechnical Awareness for Operatives Certificate",
                                "skillId": 2375,
                            },
                            {"name": "Dredging Experience", "skillId": 2435},
                            {"name": "Leveling Experience", "skillId": 2436},
                            {"name": "Breaker Experience", "skillId": 2437},
                        ],
                    },
                    {
                        "name": "360 Excavator Operator Below 10t - Tracked",
                        "subCategoryId": 58284,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2344},
                            {"name": "CPCS Red", "skillId": 2345},
                            {"name": "CSCS Card", "skillId": 2346},
                            {"name": "NPORS", "skillId": 2347},
                            {
                                "name": "Geotechnical Awareness for Operatives Certificate",
                                "skillId": 2376,
                            },
                            {"name": "Dredging Experience", "skillId": 2438},
                            {"name": "Leveling Experience", "skillId": 2439},
                            {"name": "Breaker Experience", "skillId": 2440},
                        ],
                    },
                    {
                        "name": "360 Excavator Operator Below10t - Wheeled (Rubber Duck)",
                        "subCategoryId": 58283,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2348},
                            {"name": "CPCS Red", "skillId": 2349},
                            {"name": "CSCS Card", "skillId": 2350},
                            {"name": "NPORS", "skillId": 2351},
                            {
                                "name": "Geotechnical Awareness for Operatives Certificate",
                                "skillId": 2377,
                            },
                            {"name": "Dredging Experience", "skillId": 2441},
                            {"name": "Leveling Experience", "skillId": 2442},
                            {"name": "Breaker Experience", "skillId": 2443},
                        ],
                    },
                    {
                        "name": "ADT - Articulated Dump Truck Operator",
                        "subCategoryId": 50379,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2363},
                            {"name": "CPCS Red", "skillId": 2364},
                            {"name": "CSCS Card", "skillId": 2365},
                            {"name": "NPORS", "skillId": 2366},
                        ],
                    },
                    {
                        "name": "Agricultural Tractor Operator",
                        "subCategoryId": 50380,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2359},
                            {"name": "CPCS Red", "skillId": 2360},
                            {"name": "CSCS Card", "skillId": 2361},
                            {"name": "NPORS", "skillId": 2362},
                        ],
                    },
                    {
                        "name": "Banksman/Slinger",
                        "subCategoryId": 83365,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 4609},
                            {"name": "Traffic Marshal Qualification", "skillId": 4610},
                            {"name": "CPCS - RED", "skillId": 4611},
                            {"name": "CPCS - BLUE", "skillId": 4613},
                        ],
                    },
                    {
                        "name": "Counter Balance Forklift",
                        "subCategoryId": 83363,
                        "skills": [
                            {"name": "CPCS - RED", "skillId": 4601},
                            {"name": "CPCS - BLUE", "skillId": 4602},
                            {"name": "CSCS Card", "skillId": 4603},
                            {"name": "NPORS", "skillId": 4604},
                        ],
                    },
                    {
                        "name": "Dozer Operator",
                        "subCategoryId": 50381,
                        "skills": [
                            {"name": "CPCS Blue", "skillId": 2367},
                            {"name": "CPCS Red", "skillId": 2368},
                            {"name": "CSCS Card", "skillId": 2369},
                            {"name": "NPORS", "skillId": 2370},
                        ],
                    },
                    {
                        "name": "Forklift",
                        "subCategoryId": 83360,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 4597},
                            {"name": "CPCS - BLUE", "skillId": 4598},
                            {"name": "CPCS - RED", "skillId": 4599},
                            {"name": "NPORS", "skillId": 4600},
                        ],
                    },
                    {
                        "name": "Forward Tipping Dumper Operator",
                        "subCategoryId": 58287,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 2466},
                            {"name": "CPCS - BLUE", "skillId": 2467},
                            {"name": "CPCS - RED", "skillId": 2468},
                            {"name": "NPORS", "skillId": 2469},
                        ],
                    },
                    {"name": "Grader", "subCategoryId": 198413},
                    {
                        "name": "Labourer",
                        "subCategoryId": 36214,
                        "skills": [{"name": "CSCS Card", "skillId": 2413}],
                    },
                    {
                        "name": "Loading Shovel Operator",
                        "subCategoryId": 48181,
                        "skills": [
                            {"name": "CPCS - RED", "skillId": 2091},
                            {"name": "CPCS - BLUE", "skillId": 2092},
                            {"name": "NPORS", "skillId": 2093},
                            {"name": "CSCS Card", "skillId": 2094},
                            {"name": "MPQC", "skillId": 2095},
                        ],
                    },
                    {
                        "name": "Maintenance Operative",
                        "subCategoryId": 50375,
                        "skills": [{"name": "CSCS Card", "skillId": 2414}],
                    },
                    {
                        "name": "Plant Fitter",
                        "subCategoryId": 50363,
                        "skills": [{"name": "CSCS Card", "skillId": 2419}],
                    },
                    {
                        "name": "Rigid Dump Truck Tracked Operator",
                        "subCategoryId": 50368,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 2449},
                            {"name": "CPCS - BLUE", "skillId": 2450},
                            {"name": "CPCS - RED", "skillId": 2451},
                            {"name": "100T Experience", "skillId": 2452},
                            {"name": "NPORS", "skillId": 2453},
                        ],
                    },
                    {
                        "name": "Rigid Dump Truck Wheeled Operator",
                        "subCategoryId": 50369,
                        "skills": [
                            {"name": "CPCS - RED", "skillId": 2454},
                            {"name": "CPCS - BLUE", "skillId": 2455},
                            {"name": "NPORS", "skillId": 2456},
                            {"name": "CSCS Card", "skillId": 2457},
                            {"name": "100T Experience", "skillId": 2458},
                        ],
                    },
                    {
                        "name": "Roller Operator",
                        "subCategoryId": 50370,
                        "skills": [
                            {"name": "CPCS - RED", "skillId": 2459},
                            {"name": "CPCS - BLUE", "skillId": 2460},
                            {"name": "NPORS", "skillId": 2461},
                            {"name": "CSCS Card", "skillId": 2462},
                        ],
                    },
                    {
                        "name": "Skid Steer Loader",
                        "subCategoryId": 83366,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 4614},
                            {"name": "CPCS - BLUE", "skillId": 4615},
                            {"name": "CPCS - RED", "skillId": 4616},
                            {"name": "NPORS", "skillId": 4617},
                        ],
                    },
                    {"name": "Skilled Groundworker", "subCategoryId": 195514},
                    {
                        "name": "Telehandler Operator",
                        "subCategoryId": 58288,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 2470},
                            {"name": "CPCS - BLUE", "skillId": 2471},
                            {"name": "CPCS - RED", "skillId": 2472},
                            {"name": "NPORS", "skillId": 2473},
                        ],
                    },
                    {
                        "name": "Telescopic Forklift",
                        "subCategoryId": 83364,
                        "skills": [
                            {"name": "CSCS Card", "skillId": 4605},
                            {"name": "CPCS - BLUE", "skillId": 4606},
                            {"name": "CPCS - RED", "skillId": 4607},
                            {"name": "NPORS", "skillId": 4608},
                        ],
                    },
                    {"name": "Weighbridge Operator", "subCategoryId": 50382},
                    {"name": "Screener/Crusher", "subCategoryId": 198414},
                ],
            },
            {
                "categoryId": 15643,
                "name": "Construction Trades",
                "subCategories": [
                    {"name": "Bricklayer", "subCategoryId": 195509},
                    {"name": "Carpenter", "subCategoryId": 195506},
                    {
                        "name": "Electrician",
                        "subCategoryId": 195507,
                        "skills": [
                            {"name": "18th Edition", "skillId": 31000},
                            {"name": "17th Edition", "skillId": 31001},
                        ],
                    },
                    {
                        "name": "Joiner",
                        "subCategoryId": 195505,
                        "skills": [
                            {
                                "name": "CPCS Gold Card / Minimum SVQ2 or NVQ2 Certificate or higher",
                                "skillId": 31002,
                            },
                            {"name": "City & Guilds", "skillId": 31003},
                            {
                                "name": "CPCS Blue Carpentry or Joinery Card",
                                "skillId": 31004,
                            },
                        ],
                    },
                    {"name": "Maintenance Engineer", "subCategoryId": 198411},
                    {"name": "Painter & Decorator", "subCategoryId": 198409},
                    {"name": "Pipefitter", "subCategoryId": 195512},
                    {"name": "Plumber", "subCategoryId": 195508},
                    {"name": "Roofer", "subCategoryId": 195510},
                    {"name": "Site Manager SMSTS", "subCategoryId": 198410},
                    {"name": "Site Supervisor SSSTS", "subCategoryId": 195513},
                    {"name": "Welder", "subCategoryId": 195511},
                    {"name": "Maintenance Operative", "subCategoryId": 198412},
                    {"name": "Glazier", "subCategoryId": 470933},
                    {"name": "Plasterer", "subCategoryId": 470934},
                    {"name": "Scaffolder", "subCategoryId": 509737},
                    {"name": "Fire Stopper", "subCategoryId": 565169},
                ],
            },
            {
                "categoryId": 3229,
                "name": "Defence / Emergency / Security",
                "subCategories": [
                    {"name": "Army / Navy / Air Force", "subCategoryId": 36226},
                    {"name": "Correctional Services", "subCategoryId": 36227},
                    {"name": "Crowd Control", "subCategoryId": 36228},
                    {"name": "Emergency Services", "subCategoryId": 36229},
                    {"name": "Police / Fire / Ambulance", "subCategoryId": 36230},
                    {"name": "Security Guards / Officers", "subCategoryId": 36231},
                    {"name": "Security - Other", "subCategoryId": 36232},
                ],
            },
            {
                "categoryId": 3230,
                "name": "Education & Child Care",
                "subCategories": [
                    {"name": "Au Pair / Nanny", "subCategoryId": 36233},
                    {"name": "Childcare", "subCategoryId": 36234},
                    {"name": "Early Childhood - Other", "subCategoryId": 36235},
                    {"name": "Languages / Translator", "subCategoryId": 36236},
                    {"name": "Lecturer / Professor", "subCategoryId": 36237},
                    {"name": "Library", "subCategoryId": 36238},
                    {"name": "Primary - Other", "subCategoryId": 36242},
                    {"name": "Primary - Teachers", "subCategoryId": 36243},
                    {"name": "Principal", "subCategoryId": 36244},
                    {"name": "Research", "subCategoryId": 36245},
                    {"name": "Secondary - Other", "subCategoryId": 36246},
                    {"name": "Secondary - Teachers", "subCategoryId": 36247},
                    {"name": "Student Services", "subCategoryId": 36239},
                    {"name": "Tutor", "subCategoryId": 36240},
                    {"name": "University - Other", "subCategoryId": 36241},
                ],
            },
            {
                "categoryId": 3231,
                "name": "Engineering",
                "subCategories": [
                    {"name": "Aeronautics", "subCategoryId": 36261},
                    {"name": "Automotive", "subCategoryId": 36262},
                    {"name": "Building Services", "subCategoryId": 36263},
                    {"name": "CAD / CAE", "subCategoryId": 36264},
                    {"name": "Chemical / Process", "subCategoryId": 36265},
                    {"name": "Civil / Structural / Design", "subCategoryId": 36255},
                    {"name": "Electrical", "subCategoryId": 36256},
                    {"name": "Environmental", "subCategoryId": 36257},
                    {"name": "Field", "subCategoryId": 36258},
                    {"name": "Industrial", "subCategoryId": 36259},
                    {"name": "Maintenance", "subCategoryId": 36260},
                    {"name": "Management", "subCategoryId": 36249},
                    {"name": "Mechanical", "subCategoryId": 36250},
                    {"name": "Project Management", "subCategoryId": 36251},
                    {"name": "Surveyor", "subCategoryId": 36252},
                    {"name": "Systems", "subCategoryId": 36253},
                    {"name": "Water & Waste", "subCategoryId": 36254},
                    {"name": "Engineering - Other", "subCategoryId": 36248},
                ],
            },
            {
                "categoryId": 3232,
                "name": "Executive Management",
                "subCategories": [
                    {"name": "Chairman", "subCategoryId": 36275},
                    {"name": "Chief Executive Officer (CEO)", "subCategoryId": 36276},
                    {"name": "Chief Financial Officer (CFO)", "subCategoryId": 36277},
                    {"name": "Chief Information Officer", "subCategoryId": 36269},
                    {"name": "Chief Operating Officer (COO)", "subCategoryId": 36270},
                    {"name": "Company Secretary", "subCategoryId": 36271},
                    {"name": "Director", "subCategoryId": 36272},
                    {"name": "Finance Director (FD)", "subCategoryId": 36273},
                    {"name": "General Manager", "subCategoryId": 36274},
                    {"name": "Managing Director", "subCategoryId": 36266},
                    {"name": "Partner", "subCategoryId": 36267},
                    {"name": "Other", "subCategoryId": 36268},
                ],
            },
            {
                "categoryId": 3233,
                "name": "Government / Local Government",
                "subCategories": [
                    {"name": "Federal Government", "subCategoryId": 36278},
                    {"name": "Local Government", "subCategoryId": 36279},
                    {"name": "State Government", "subCategoryId": 36280},
                ],
            },
            {
                "categoryId": 3234,
                "name": "Graduates",
                "subCategories": [
                    {"name": "Accounting", "subCategoryId": 36281},
                    {"name": "Admin / Secretarial / Office", "subCategoryId": 36282},
                    {"name": "Advertising/Media/Publishing", "subCategoryId": 36283},
                    {"name": "Architecture & Interior Design", "subCategoryId": 36284},
                    {"name": "Arts & Entertainment", "subCategoryId": 36285},
                    {"name": "Banking & Finance", "subCategoryId": 36286},
                    {"name": "Building & Construction", "subCategoryId": 36304},
                    {"name": "Call Centre & Customer Service", "subCategoryId": 36305},
                    {"name": "Defence / Emergency / Security", "subCategoryId": 36306},
                    {"name": "Education & Child Care", "subCategoryId": 36307},
                    {"name": "Engineering", "subCategoryId": 36308},
                    {"name": "Government / Local Government", "subCategoryId": 36309},
                    {"name": "Healthcare & Medicine", "subCategoryId": 36298},
                    {"name": "Hospitality / Travel / Tourism", "subCategoryId": 36299},
                    {"name": "HR & Recruitment", "subCategoryId": 36300},
                    {"name": "Insurance & Superannuation", "subCategoryId": 36301},
                    {"name": "IT & Telecomms", "subCategoryId": 36302},
                    {"name": "Legal", "subCategoryId": 36303},
                    {"name": "Manufacturing", "subCategoryId": 36292},
                    {"name": "Marketing / PR / Events", "subCategoryId": 36293},
                    {"name": "Mining / Oil & Gas / Utilities", "subCategoryId": 36294},
                    {"name": "Multimedia / Design / New Media", "subCategoryId": 36295},
                    {"name": "Real Estate + Property", "subCategoryId": 36296},
                    {"name": "Retail", "subCategoryId": 36297},
                    {"name": "Sales & Account Management", "subCategoryId": 36287},
                    {"name": "Science & Biotechnology", "subCategoryId": 36288},
                    {"name": "Sport & Recreation", "subCategoryId": 36289},
                    {"name": "Trades & Services", "subCategoryId": 36290},
                    {"name": "Transport / Logistics / Drivers", "subCategoryId": 36291},
                ],
            },
            {
                "categoryId": 3235,
                "name": "Healthcare & Medicine",
                "subCategories": [
                    {"name": "Administration / Admissions", "subCategoryId": 36310},
                    {"name": "Aged Care", "subCategoryId": 36311},
                    {"name": "Alternative Medicine", "subCategoryId": 36312},
                    {"name": "Ambulance / Paramedic", "subCategoryId": 36313},
                    {"name": "Chiropractor", "subCategoryId": 36314},
                    {"name": "Clinical / Medical Research", "subCategoryId": 36315},
                    {"name": "Critical Care", "subCategoryId": 36330},
                    {"name": "Dental", "subCategoryId": 36331},
                    {"name": "Management", "subCategoryId": 36332},
                    {"name": "Medical Practitioner", "subCategoryId": 36333},
                    {"name": "Medical Sales", "subCategoryId": 36334},
                    {"name": "Medical Specialist", "subCategoryId": 36335},
                    {"name": "Mental Health", "subCategoryId": 36324},
                    {"name": "Nurse / Midwive", "subCategoryId": 36325},
                    {"name": "Oncology", "subCategoryId": 36326},
                    {"name": "Optometry", "subCategoryId": 36327},
                    {"name": "Pathology", "subCategoryId": 36328},
                    {"name": "Pharmaceuticals", "subCategoryId": 36329},
                    {"name": "Pharmacy / Chemist", "subCategoryId": 36318},
                    {"name": "Physio / Occupational Therapy", "subCategoryId": 36319},
                    {"name": "Psychology", "subCategoryId": 36320},
                    {"name": "Radiology / Sonography", "subCategoryId": 36321},
                    {"name": "Speech Therapy", "subCategoryId": 36322},
                    {"name": "Surgical", "subCategoryId": 36323},
                    {"name": "Vets / Vet Science", "subCategoryId": 36316},
                    {"name": "Other", "subCategoryId": 36317},
                ],
            },
            {
                "categoryId": 3236,
                "name": "Hospitality / Travel / Tourism",
                "subCategories": [
                    {"name": "Airline / Flight Attendant", "subCategoryId": 36336},
                    {"name": "Bar and Beverage", "subCategoryId": 36337},
                    {"name": "Chef", "subCategoryId": 36338},
                    {"name": "Cook", "subCategoryId": 36339},
                    {"name": "Front Office", "subCategoryId": 36340},
                    {"name": "Gaming & Hotel", "subCategoryId": 36341},
                    {"name": "Kitchen Hand", "subCategoryId": 36344},
                    {"name": "Management / Supervisor", "subCategoryId": 36345},
                    {"name": "Pilot", "subCategoryId": 36346},
                    {"name": "Tour Bus Driver", "subCategoryId": 36347},
                    {"name": "Tour Guide & Operator", "subCategoryId": 36348},
                    {"name": "Travel Agent / Consultant", "subCategoryId": 36349},
                    {"name": "Wait Staff", "subCategoryId": 36342},
                    {"name": "Other", "subCategoryId": 36343},
                ],
            },
            {
                "categoryId": 3237,
                "name": "Hr & Recruitment",
                "subCategories": [
                    {"name": "HR - Assistant / Administrator", "subCategoryId": 36350},
                    {"name": "HR - Co-ordinator", "subCategoryId": 36351},
                    {"name": "HR - Officer / Adviser", "subCategoryId": 36352},
                    {"name": "HR - Consultant", "subCategoryId": 36353},
                    {"name": "HR - General", "subCategoryId": 36354},
                    {"name": "HR - Management", "subCategoryId": 36355},
                    {"name": "HR - Director / Head of HR", "subCategoryId": 36377},
                    {"name": "OH & S", "subCategoryId": 36378},
                    {
                        "name": "Training / Learning & Development",
                        "subCategoryId": 36379,
                    },
                    {"name": "OD - Organisational Development", "subCategoryId": 36380},
                    {
                        "name": "Remuneration and Benefits Specialist",
                        "subCategoryId": 36381,
                    },
                    {"name": "Industrial Relations Specialist", "subCategoryId": 36382},
                    {"name": "Payroll Officer", "subCategoryId": 36371},
                    {"name": "HRIS", "subCategoryId": 36372},
                    {"name": "HR - Other", "subCategoryId": 36373},
                    {"name": "Recruitment - Account Manager", "subCategoryId": 36374},
                    {"name": "Recruitment - Manager", "subCategoryId": 36375},
                    {"name": "Recruitment - Support/Other", "subCategoryId": 36376},
                    {"name": "Recruitment Consultant - Perm", "subCategoryId": 36365},
                    {
                        "name": "Recruitment Consultant - Temp / Contract",
                        "subCategoryId": 36366,
                    },
                    {"name": "Resourcer", "subCategoryId": 36367},
                    {"name": "Researcher", "subCategoryId": 36368},
                    {"name": "Senior Recruitment Consultant", "subCategoryId": 36369},
                    {"name": "State / Country Manager", "subCategoryId": 36370},
                    {"name": "Team Leader", "subCategoryId": 36359},
                    {"name": "Trainee Consultant", "subCategoryId": 36360},
                    {"name": "Recruitment - Other", "subCategoryId": 36361},
                    {"name": "Executive Search Consultant", "subCategoryId": 36362},
                    {"name": "Office Manager", "subCategoryId": 36363},
                    {"name": "Recruitment Centre Manager", "subCategoryId": 36364},
                    {"name": "Recruitment Team Leader", "subCategoryId": 36356},
                    {"name": "Senior Internal Recruiter", "subCategoryId": 36357},
                    {"name": "Internal Recruiter", "subCategoryId": 36358},
                ],
            },
            {
                "categoryId": 3238,
                "name": "Insurance",
                "subCategories": [
                    {"name": "Actuary", "subCategoryId": 36383},
                    {"name": "Insurance - Broker", "subCategoryId": 36384},
                    {"name": "Insurance - Claims & Assessors", "subCategoryId": 36385},
                    {"name": "Insurance - General", "subCategoryId": 36386},
                    {"name": "Insurance - Life / Health", "subCategoryId": 36387},
                    {"name": "Management", "subCategoryId": 36388},
                    {"name": "Underwriting", "subCategoryId": 36389},
                    {"name": "Workers Compensation", "subCategoryId": 36390},
                    {"name": "Other", "subCategoryId": 36391},
                ],
            },
            {
                "categoryId": 3239,
                "name": "IT & Telecomms",
                "subCategories": [
                    {"name": "Architect", "subCategoryId": 36392},
                    {"name": "Business Analyst", "subCategoryId": 36393},
                    {"name": "Consultant - BI / CRM", "subCategoryId": 36394},
                    {"name": "Consultant - ERP / Supply Chain", "subCategoryId": 36395},
                    {"name": "Consultant - Other", "subCategoryId": 36396},
                    {"name": "Consultant - Pre Sales", "subCategoryId": 36397},
                    {"name": "Data / Records Management", "subCategoryId": 36415},
                    {"name": "DBA / Database Developer", "subCategoryId": 36416},
                    {"name": "Hardware Engineer", "subCategoryId": 36417},
                    {"name": "Help Desk / Support", "subCategoryId": 36418},
                    {"name": "IT Security", "subCategoryId": 36419},
                    {"name": "Management", "subCategoryId": 36420},
                    {"name": "Network Administration", "subCategoryId": 36409},
                    {"name": "Network Engineer", "subCategoryId": 36410},
                    {"name": "Project Management / Team Lead", "subCategoryId": 36411},
                    {"name": "Sales Exec / Account Manager", "subCategoryId": 36412},
                    {"name": "Software - Analyst/Programmer", "subCategoryId": 36413},
                    {"name": "Software - Architect", "subCategoryId": 36414},
                    {"name": "Software - Developer", "subCategoryId": 36403},
                    {"name": "System Administration", "subCategoryId": 36404},
                    {"name": "Systems Analyst", "subCategoryId": 36405},
                    {"name": "Systems Integration", "subCategoryId": 36406},
                    {"name": "Technical Writer / Documenter", "subCategoryId": 36407},
                    {"name": "Testing & QA", "subCategoryId": 36408},
                    {"name": "Trainer", "subCategoryId": 36398},
                    {"name": "WAN / Telecommunications", "subCategoryId": 36399},
                    {"name": "Web / Multimedia Designer", "subCategoryId": 36400},
                    {"name": "Web / Multimedia Developer", "subCategoryId": 36401},
                    {"name": "IT - Other", "subCategoryId": 36402},
                ],
            },
            {
                "categoryId": 3240,
                "name": "Legal",
                "subCategories": [
                    {"name": "Law Clerk / Paralegal", "subCategoryId": 36421},
                    {"name": "Lawyer - Commercial", "subCategoryId": 36422},
                    {"name": "Lawyer - Compliance", "subCategoryId": 36423},
                    {"name": "Lawyer - Corporate / M&A", "subCategoryId": 36424},
                    {"name": "Lawyer - Employment", "subCategoryId": 36425},
                    {"name": "Lawyer - Inhouse", "subCategoryId": 36426},
                    {"name": "Lawyer - IP / Trademark", "subCategoryId": 36432},
                    {"name": "Lawyer - Litigation", "subCategoryId": 36433},
                    {"name": "Lawyer - Personal Injury", "subCategoryId": 36434},
                    {"name": "Lawyer - Private Practice Other", "subCategoryId": 36435},
                    {
                        "name": "Lawyer - Property / Construction",
                        "subCategoryId": 36436,
                    },
                    {"name": "Lawyer - Public Practice", "subCategoryId": 36437},
                    {"name": "Lawyer - Tax", "subCategoryId": 36427},
                    {"name": "Legal Secretary / Admin", "subCategoryId": 36428},
                    {"name": "Partner / Manager", "subCategoryId": 36429},
                    {"name": "Solicitor", "subCategoryId": 36430},
                    {"name": "Legal - Other", "subCategoryId": 36431},
                ],
            },
            {
                "categoryId": 3241,
                "name": "Manufacturing",
                "subCategories": [
                    {"name": "Assembly Line / Assembler", "subCategoryId": 36438},
                    {"name": "Engineer", "subCategoryId": 36439},
                    {"name": "Fitting / Machining", "subCategoryId": 36440},
                    {"name": "Industrial Design", "subCategoryId": 36441},
                    {"name": "Machinery / Tool Operation", "subCategoryId": 36442},
                    {"name": "Management / Supervisor", "subCategoryId": 36443},
                    {"name": "Manufacturing Consultant", "subCategoryId": 36450},
                    {"name": "Packer / Filler", "subCategoryId": 36451},
                    {"name": "Planning", "subCategoryId": 36452},
                    {"name": "Plant Management", "subCategoryId": 36453},
                    {"name": "Process Work", "subCategoryId": 36454},
                    {"name": "Production Worker", "subCategoryId": 36455},
                    {"name": "Purchasing / Procurement", "subCategoryId": 36444},
                    {"name": "QA", "subCategoryId": 36445},
                    {"name": "Research & Development", "subCategoryId": 36446},
                    {"name": "Stores & Warehousing", "subCategoryId": 36447},
                    {"name": "Toolmaker", "subCategoryId": 36448},
                    {"name": "Other", "subCategoryId": 36449},
                ],
            },
            {
                "categoryId": 3242,
                "name": "Marketing / PR / Events",
                "subCategories": [
                    {"name": "Brand Manager", "subCategoryId": 36456},
                    {"name": "Category Manager", "subCategoryId": 36457},
                    {"name": "Database Analyst / Specialist", "subCategoryId": 36458},
                    {"name": "Direct Marketer", "subCategoryId": 36459},
                    {"name": "E-Marketing", "subCategoryId": 36460},
                    {"name": "Event / Conference Management", "subCategoryId": 36461},
                    {"name": "Event / Conference Producer", "subCategoryId": 36470},
                    {
                        "name": "Marketing Assistant / Coordinator",
                        "subCategoryId": 36471,
                    },
                    {"name": "Marketing Consultant", "subCategoryId": 36472},
                    {"name": "Marketing Director", "subCategoryId": 36473},
                    {"name": "Marketing Executive", "subCategoryId": 36474},
                    {"name": "Marketing Manager", "subCategoryId": 36475},
                    {"name": "Marketing Research", "subCategoryId": 36464},
                    {"name": "PR - Media Advisor", "subCategoryId": 36465},
                    {"name": "PR - Press Officer", "subCategoryId": 36466},
                    {"name": "PR Manager", "subCategoryId": 36467},
                    {
                        "name": "Product Development / Management",
                        "subCategoryId": 36468,
                    },
                    {"name": "Promotions", "subCategoryId": 36469},
                    {"name": "Trade Marketing", "subCategoryId": 36462},
                    {"name": "Marketing / PR / Events - Other", "subCategoryId": 36463},
                ],
            },
            {
                "categoryId": 3243,
                "name": "Mining / Oil & Gas / Utilities",
                "subCategories": [
                    {"name": "Drilling & Blast", "subCategoryId": 36476},
                    {"name": "Engineering & Maintenance", "subCategoryId": 36477},
                    {"name": "Exploration", "subCategoryId": 36478},
                    {"name": "Geoscience", "subCategoryId": 36479},
                    {"name": "Labourer", "subCategoryId": 36480},
                    {"name": "Manager / Supervisor", "subCategoryId": 36481},
                    {"name": "Mineral Processing", "subCategoryId": 36482},
                    {"name": "Production", "subCategoryId": 36483},
                    {"name": "Utilities", "subCategoryId": 36484},
                    {"name": "Other", "subCategoryId": 36485},
                ],
            },
            {
                "categoryId": 3244,
                "name": "Multimedia / Design / New Media",
                "subCategories": [
                    {"name": "3D / Special Effects", "subCategoryId": 36486},
                    {"name": "Content / Editorial", "subCategoryId": 36487},
                    {"name": "Creative", "subCategoryId": 36488},
                    {"name": "Designer", "subCategoryId": 36489},
                    {"name": "Gaming", "subCategoryId": 36490},
                    {"name": "Information Architect", "subCategoryId": 36491},
                    {"name": "Management", "subCategoryId": 36492},
                    {"name": "Other", "subCategoryId": 36493},
                ],
            },
            {
                "categoryId": 3245,
                "name": "Real Estate & Property",
                "subCategories": [
                    {"name": "Admin / Office Support", "subCategoryId": 36494},
                    {"name": "Broker", "subCategoryId": 36495},
                    {"name": "Commercial", "subCategoryId": 36496},
                    {"name": "Facilities Manager", "subCategoryId": 36497},
                    {"name": "Leasing", "subCategoryId": 36498},
                    {"name": "Property Management", "subCategoryId": 36499},
                    {"name": "Residential", "subCategoryId": 36500},
                    {"name": "Sales / Agents", "subCategoryId": 36501},
                    {"name": "Valuation", "subCategoryId": 36502},
                    {"name": "Real Estate - Other", "subCategoryId": 36503},
                ],
            },
            {
                "categoryId": 3246,
                "name": "Retail",
                "subCategories": [
                    {"name": "Buyer / Purchaser", "subCategoryId": 36504},
                    {"name": "Department Manager", "subCategoryId": 36505},
                    {"name": "Duty Manager", "subCategoryId": 36506},
                    {"name": "Loss Prevention", "subCategoryId": 36507},
                    {"name": "Management - Head Office", "subCategoryId": 36508},
                    {"name": "Merchandising", "subCategoryId": 36509},
                    {"name": "Retail Assistant", "subCategoryId": 36510},
                    {"name": "Sales Assistant", "subCategoryId": 36511},
                    {"name": "Store Manager / Supervisor", "subCategoryId": 36512},
                    {"name": "Retail - Other", "subCategoryId": 36513},
                ],
            },
            {
                "categoryId": 3247,
                "name": "Sales & Account Management",
                "subCategories": [
                    {"name": "Area / Territory Manager", "subCategoryId": 36514},
                    {"name": "Key Account Manager", "subCategoryId": 36515},
                    {"name": "Sales Assistant / Coordinator", "subCategoryId": 36516},
                    {"name": "Sales Executive / BDM", "subCategoryId": 36517},
                    {"name": "Sales Manager", "subCategoryId": 36518},
                    {"name": "Sales Rep", "subCategoryId": 36519},
                    {"name": "Telemarketing", "subCategoryId": 36520},
                    {"name": "Telesales", "subCategoryId": 36521},
                    {"name": "Sales - Other", "subCategoryId": 36522},
                ],
            },
            {
                "categoryId": 3248,
                "name": "Science & Biotechnology",
                "subCategories": [
                    {"name": "Biotech", "subCategoryId": 36523},
                    {"name": "Environmental", "subCategoryId": 36524},
                    {"name": "Food", "subCategoryId": 36525},
                    {"name": "Laboratory / Technical", "subCategoryId": 36526},
                    {"name": "Pharmaceutical", "subCategoryId": 36527},
                    {"name": "Quality Assurance / Testing", "subCategoryId": 36528},
                    {"name": "Research & Development", "subCategoryId": 36529},
                    {"name": "Scientist - Other", "subCategoryId": 36530},
                    {"name": "Topography", "subCategoryId": 36531},
                    {"name": "Other", "subCategoryId": 36532},
                ],
            },
            {
                "categoryId": 3249,
                "name": "Sport & Recreation",
                "subCategories": [
                    {"name": "Coach / Instructor", "subCategoryId": 36533},
                    {"name": "Fitness Centre Manager", "subCategoryId": 36534},
                    {"name": "Fitness Instructor / Trainer", "subCategoryId": 36535},
                    {"name": "Management", "subCategoryId": 36536},
                    {"name": "Masseuse", "subCategoryId": 36537},
                    {"name": "Operations Manager", "subCategoryId": 36538},
                    {"name": "Sales", "subCategoryId": 36539},
                    {"name": "Sport and Rec - Other", "subCategoryId": 36540},
                ],
            },
            {
                "categoryId": 3250,
                "name": "Trades & Services",
                "subCategories": [
                    {"name": "Aircon / Refrigeration", "subCategoryId": 36541},
                    {"name": "Apprentice / Trainee", "subCategoryId": 36542},
                    {"name": "Baker", "subCategoryId": 36543},
                    {"name": "Beauty Therapist / Beautician", "subCategoryId": 36544},
                    {"name": "Boat / Marine Specialist", "subCategoryId": 36545},
                    {"name": "Boilermaker", "subCategoryId": 36546},
                    {"name": "Bricklayer", "subCategoryId": 36570},
                    {"name": "Builder", "subCategoryId": 36571},
                    {"name": "Butcher", "subCategoryId": 36572},
                    {"name": "Carpenter / Cabinet Maker", "subCategoryId": 36573},
                    {"name": "Carpet Fitter", "subCategoryId": 36574},
                    {"name": "Catering / Beverage", "subCategoryId": 36575},
                    {"name": "Chef", "subCategoryId": 36564},
                    {"name": "Cleaner", "subCategoryId": 36565},
                    {"name": "Concrete / Formwork", "subCategoryId": 36566},
                    {"name": "Courier", "subCategoryId": 36567},
                    {"name": "Demolition / Excavation", "subCategoryId": 36568},
                    {"name": "Electrician", "subCategoryId": 36569},
                    {"name": "Floristry", "subCategoryId": 36558},
                    {"name": "Funeral Services", "subCategoryId": 36559},
                    {
                        "name": "Gardener / Landscaper / Horticulturalist",
                        "subCategoryId": 36560,
                    },
                    {"name": "Glazier", "subCategoryId": 36561},
                    {"name": "Hair Dresser", "subCategoryId": 36562},
                    {"name": "Labourer", "subCategoryId": 36563},
                    {"name": "Maintenance / Handypeople", "subCategoryId": 36552},
                    {"name": "Mechanic / Automotive", "subCategoryId": 36553},
                    {"name": "Painting", "subCategoryId": 36554},
                    {"name": "Pest Control Specialist", "subCategoryId": 36555},
                    {"name": "Plumbing", "subCategoryId": 36556},
                    {"name": "Printing", "subCategoryId": 36557},
                    {"name": "Removalist", "subCategoryId": 36547},
                    {"name": "Technician", "subCategoryId": 36548},
                    {"name": "Welder / Metalworker", "subCategoryId": 36549},
                    {"name": "Services - Other", "subCategoryId": 36550},
                    {"name": "Trades - Other", "subCategoryId": 36551},
                ],
            },
            {
                "categoryId": 3251,
                "name": "Transport / Logistics / Drivers",
                "subCategories": [
                    {"name": "Administration", "subCategoryId": 36576},
                    {"name": "Aviation", "subCategoryId": 36577},
                    {"name": "Customs", "subCategoryId": 36578},
                    {
                        "name": "Driver",
                        "subCategoryId": 36579,
                        "skills": [
                            {"name": "LGV1", "skillId": 91537},
                            {"name": "LGV2", "skillId": 91539},
                            {"name": "7.5tonne", "skillId": 91542},
                            {"name": "NLGV", "skillId": 91543},
                            {"name": "ADR", "skillId": 91545},
                            {"name": "HIAB", "skillId": 91546},
                            {"name": "Forklift C/B", "skillId": 91544},
                            {"name": "Forklift Reach", "skillId": 91547},
                        ],
                    },
                    {"name": "Fleet Management", "subCategoryId": 36580},
                    {"name": "Freight Forwarding / Shipping", "subCategoryId": 36581},
                    {"name": "Importer / Exporter", "subCategoryId": 36587},
                    {"name": "Management", "subCategoryId": 36588},
                    {"name": "Operations", "subCategoryId": 36589},
                    {"name": "Planning", "subCategoryId": 36590},
                    {"name": "Purchasing", "subCategoryId": 36591},
                    {"name": "Stevedoring", "subCategoryId": 36592},
                    {"name": "Support / Customer Service", "subCategoryId": 36582},
                    {"name": "Transport", "subCategoryId": 36583},
                    {"name": "Warehouse & Distribution", "subCategoryId": 36584},
                    {"name": "Logistics - Other", "subCategoryId": 36585},
                    {"name": "Supply Chain - Other", "subCategoryId": 36586},
                ],
            },
            {
                "categoryId": 3252,
                "name": "Volunteer / Charity / Community",
                "subCategories": [
                    {"name": "Charity", "subCategoryId": 36593},
                    {"name": "Church / Religious", "subCategoryId": 36594},
                    {"name": "Counsellor", "subCategoryId": 36595},
                    {"name": "Fundraising", "subCategoryId": 36596},
                    {"name": "Social Work", "subCategoryId": 36597},
                    {"name": "Support Services", "subCategoryId": 36598},
                    {"name": "Volunteer", "subCategoryId": 36599},
                    {"name": "Other", "subCategoryId": 36600},
                ],
            },
        ]
    }
